# Numpy (Numerical Python) :

In [2]:
import numpy as np
x = np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [3]:
x/2

array([1., 2., 3., 4., 5.])

In [4]:
x*2

array([ 4,  8, 12, 16, 20])

In [5]:
x = [2,4,6,8,10]
for i in x:
    print(i/2)

1.0
2.0
3.0
4.0
5.0


In [9]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
import numpy as np
np.random.randint(0,10,4)

array([7, 0, 1, 1])

In [12]:
import numpy as np
array = np.random.randint(0,10,(3,3))
array

array([[2, 2, 7],
       [8, 5, 6],
       [8, 6, 2]])

In [14]:
np.random.rand(6)

array([0.89086216, 0.80516081, 0.80266171, 0.17066283, 0.75288394,
       0.11741666])

# NUMPY SLICING OR ARRAY SLICING: 

In [15]:
data = np.random.randint(0,10,(5,4))
data

array([[1, 7, 0, 5],
       [8, 5, 3, 6],
       [2, 3, 1, 6],
       [0, 5, 7, 3],
       [3, 2, 8, 6]])

In [16]:
data[1: , :2]

array([[8, 5],
       [2, 3],
       [0, 5],
       [3, 2]])

# ARRAY:

 1 DIMENTIONAL ARRAY
, 2 DIMENTIONAL ARRAY
, 3 DIMENTIONAL ARRAY

1D ARRAY

In [17]:
import numpy as np
a = np.array({1,23,24})
print(a)

{24, 1, 23}


2D ARRAY

In [18]:
b = np.array([[2,4,6],[8,10,12]])
print(b)

[[ 2  4  6]
 [ 8 10 12]]


3D ARRAY

In [20]:
b = np.array([[2,4,6],[8,10,12],[5,6,7]]),([[1,7,3],[5,5,6],[5,8,7]])
print(b)

(array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 5,  6,  7]]), [[1, 7, 3], [5, 5, 6], [5, 8, 7]])


# INITIALIZE NUMPY ARRAY:

In [25]:
import numpy as np
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.full((4,4),-6)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

# INITIALIZE 'X' AND 'Y' WITH AN INTERVAL OF Z :

In [32]:
import numpy as np
np.arange (0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# INITIALIZE 'Z' NUMBERS BETWEEN 'X' AND 'Y':

In [35]:
np.linspace(5,10,4)

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [37]:
np.linspace (10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# EYE FUNCTIONS:

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
data = np.array([[5,4,0,1],[11,4,10,7],[7,10,5,6],[7,12,10,4],[3,7,3,4]])
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


# SUM FUNCTION :


In [41]:
data.sum()

120

# MAX FUNCTION:

In [42]:
data.max()

12

# MIN FUNCTION:

In [43]:
data.min()

0

In [44]:
data.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

# MEAN FUNCTION:

In [45]:
data.mean()

6.0

# ARRAY SHAPE:

In [47]:
a = np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


# CHANGING THE SHAPE OF ARRAY:

In [48]:
a = np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]])
print("Original Array:\n",a)
a.shape = (4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [49]:
 b = np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
b.shape = (6,2)
print(b)
print(b.ndim)
    

[[1 2]
 [3 4]
 [5 6]
 [5 8]
 [8 5]
 [6 4]]
2


In [52]:
z = np.arange(24)
z.shape = (4,2,3)
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
3


# FINDING THE NUMBER ELEMENTS IN ARRAY:

In [55]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

9
(3, 3)
2
int32


In [58]:
import numpy as np
x = np.random.randint(0,20,(6,5))
print(x)

[[ 4 16 14 13  6]
 [10 17 15  2  3]
 [ 7 13  5 10 18]
 [19 16  3  9  7]
 [ 2  1 18  2 18]
 [ 4 12  6 18 14]]


In [59]:
x.ravel()

array([ 4, 16, 14, 13,  6, 10, 17, 15,  2,  3,  7, 13,  5, 10, 18, 19, 16,
        3,  9,  7,  2,  1, 18,  2, 18,  4, 12,  6, 18, 14])

In [61]:
y = x.ravel()

In [62]:
y.reshape(10,3)

array([[ 4, 16, 14],
       [13,  6, 10],
       [17, 15,  2],
       [ 3,  7, 13],
       [ 5, 10, 18],
       [19, 16,  3],
       [ 9,  7,  2],
       [ 1, 18,  2],
       [18,  4, 12],
       [ 6, 18, 14]])

In [64]:
x1 = np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [66]:
x2 = np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [67]:
np.stack([x1,x2])

array([[[2, 3],
        [4, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [69]:
np.concatenate([x1,x2],axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [70]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

# NUMPY ARRAY MATHEMATICS:


# SUM:

In [73]:
d = np.array(10,dtype='float')
print(d)

10.0


In [74]:
import numpy as np
np.sum([10,30,60,54,63,258])

475

In [75]:
a = [10,20]
b = [20,5]
np.sum([a,b])

55

In [76]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
sum_array = array1 + array2
print("Addition:\n",sum_array)
sum_array.ndim

Addition:
 [[ 8 10 12]
 [14 16 18]]


2

# SUBTRACTION:


In [77]:
import numpy as np
np.subtract(10,20)


-10

In [79]:
a = np.array([0,1])
b=np.array([0,5])
np.subtract(a,b)

array([ 0, -4])

In [80]:
a = np.array([0,1,6])
b = np.array([0,5,3])
c = np.array([0,1,2])
sub = a-b-c
print(sub)

[ 0 -5  1]


# MULTIPLICATION:


In [87]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
product_array = array1 * array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [88]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([7,8,9])
product_array = array1 * array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 7 16 27]
 [28 40 54]]


# MATRICS MULTIPLICATION:

In [89]:
x1= np.random.randint(0,10,(2,2))
x2= np.random.randint(0,10,(2,2))
x1

array([[8, 8],
       [2, 4]])

In [90]:
x2

array([[7, 4],
       [2, 5]])

In [91]:
np.dot(x1,x2)

array([[72, 72],
       [22, 28]])

In [92]:
x1= np.random.randint(0,10,(2,3))
x2= np.random.randint(0,10,(3,2))
x1

array([[9, 1, 0],
       [1, 1, 1]])

In [93]:
x2

array([[1, 4],
       [8, 3],
       [0, 7]])

# BROADCASTING:


In [82]:
import numpy as np
a = np.array([[1,2],[6,8]])
b = np.array([5,4])
result = a+b
print("Result of a+b with broadcasting:\n",result)

Result of a+b with broadcasting:
 [[ 6  6]
 [11 12]]


# STRING FUNCTION ON ARRAYS:

In [96]:
x = np.array([1,2,3,'data'])
x

array(['1', '2', '3', 'data'], dtype='<U11')

In [97]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U11')

In [99]:
np.char.center(x,10,fillchar='*')

array(['****1*****', '****2*****', '****3*****', '***data***'],
      dtype='<U10')

In [100]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

['1' '2' '3' 'DATA']
['1' '2' '3' 'data']
['1' '2' '3' 'Data']


In [101]:
y = np.array(["Data Science","Machine Learning"])
np.char.split(y,sep='e')

array([list(['Data Sci', 'nc', '']), list(['Machin', ' L', 'arning'])],
      dtype=object)

In [103]:
np.char.count(y,"a")

array([2, 2])

In [104]:
np.char.count(y,"i")

array([1, 2])

In [105]:
np.char.startswith(y,"D")

array([ True, False])

In [106]:
np.char.startswith(y,"d")

array([False, False])

In [107]:
np.char.replace(y,'a','xxxxxxx')

array(['Dxxxxxxxtxxxxxxx Science', 'Mxxxxxxxchine Lexxxxxxxrning'],
      dtype='<U28')

In [108]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [109]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

# DIVISION:

In [110]:
array1 = np.array([[10,20,30],[40,50,60]])
array2 = np.array([[3,4,5],[10,5,3]])
division_array = array1/array2
print("Division:\n",division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


# CALCULATING THE EXPONENTIAL:

In [111]:
a = np.array([1,2,3,4,5])
exp_a  = np.exp(a)
print("Original array:",a)
print("Exponential of the array:",exp_a)

Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [112]:
a = np.array([2,4,6])
print("sqrt of a:", np.sqrt(a))
print("exp of a:", np.exp(a))
print("sin of a:", np.sin(a))
print("cos of a:", np.cos(a))
print("log of a:", np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
exp of a: [  7.3890561   54.59815003 403.42879349]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


# AGGREGRATE FUNCTION:

In [113]:
a = np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))
print("Minimum Value:",np.min(a))
print("Mean Value:",np.mean(a))
print("Median value:",np.median(a))
print("Corelation coefficient:",np.corrcoef(a))
print("Standard Deviation:",np.std(a))

Sum: 42
Minimum Value: 1
Mean Value: 5.25
Median value: 5.5
Corelation coefficient: 1.0
Standard Deviation: 2.6339134382131846


# CO-RELATION COEFFICIENT:

In [114]:
np.corrcoef(data) 

array([[ 1.        , -0.08856149,  0.7130241 ,  0.18003601,  0.33287702],
       [-0.08856149,  1.        , -0.73192505, -0.33128623, -0.94663828],
       [ 0.7130241 , -0.73192505,  1.        ,  0.52904006,  0.89665306],
       [ 0.18003601, -0.33128623,  0.52904006,  1.        ,  0.54084841],
       [ 0.33287702, -0.94663828,  0.89665306,  0.54084841,  1.        ]])